### ISSUE TITLE
InvokeHostFunctionOp/Soroban support planned?

### ISSUE THREAD

**Issue by pius** [kommitters/stellar_base#222]
### Is your feature request related to a problem? Please describe.

Stellar has [recently added](https://github.com/stellar/stellar-xdr/blob/026c9cd074bdb28ddde8ee52f2a4502d9e518a09/Stellar-transaction.x#L523-L539) a new operation, [InvokeHostFunctionOp](https://docs.rs/stellar-xdr/0.0.7/stellar_xdr/struct.InvokeHostFunctionOp.html), which is required to [support Soroban smart contracts](https://soroban.stellar.org/docs/how-to%20guides/invoking-contracts-with-transactions).

### Describe the solution you'd like

It’d be great to have `InvokeHostFunctionOp` support added for easier integration with Soroban!

**Comment by juanhurtado10** [comment]
Hey @pius. 

Yes, we will support the operation. I just created an issue for it 🚀

**Comment by juanhurtado10** [comment]
https://github.com/kommitters/stellar_base/issues/223

**Comment by pius** [comment]
That’s great news @juanhurtado10, thanks to you and the rest of the team for your hard work on this library!

**Comment by miguelnietoa** [comment]
Hey @pius, so happy to announce that:

ℹ️ We have added support for CAP-0046 in the XDR version: [df18148747e807618acf4639db41c4fd6f0be9fc](https://github.com/stellar/stellar-xdr/commit/df18148747e807618acf4639db41c4fd6f0be9fc) which corresponds to the [Soroban Preview 7](https://soroban.stellar.org/docs/reference/releases#preview-7-february-16th-2023).

**Comment by pius** [comment]
Amazing news @miguelnietoa, thanks to you, @juanhurtado10, and anyone else involved! Looking forward to checking it out!  🙌🏽

**Comment by miguelnietoa** [comment]
Hi there @pius we just released v0.12.0 of [StellarSDK](https://github.com/kommitters/stellar_sdk) adding support for Soroban Preview 7.

We are also starting the support for Soroban Preview 8 which is the latest version of Soroban at the moment.


Closing this, thank you @pius 💯

**Comment by pius** [comment]
Awesome, thanks so much for your hard work @miguelnietoa, @EdwinGuayacan
@FelipeGuzmanSierra, @juanhurtado10, @keliumJU, and @Odraxs!! 🙌🏽💯
