### ISSUE TITLE
CAP-0046 support

### ISSUE THREAD

**Issue by juanhurtado10** [kommitters/stellar_base#223]
:information_source:  This issue is an Epic

## Context
https://github.com/stellar/stellar-protocol/blob/master/core/cap-0046.md

## Objective
Add support for Soroban's smart contracts

## Checklist
- [x] #224
- [x] #228
- [x] #225
- [x] #226
- [x] #227

**Comment by miguelnietoa** [comment]
ℹ️ We have added support for CAP-0046 in the XDR version: [df18148747e807618acf4639db41c4fd6f0be9fc](https://github.com/stellar/stellar-xdr/commit/df18148747e807618acf4639db41c4fd6f0be9fc) which corresponds to the [Soroban Preview 7](https://soroban.stellar.org/docs/reference/releases#preview-7-february-16th-2023).
