### ISSUE TITLE
Allow to encode and decode TransactionMeta

### ISSUE THREAD

**Issue by Odraxs** [kommitters/stellar_base#279]
## Context

Since the field `TransactionResult` changed and doesn't return the contracts functions invocations results, now is required to add all the files necessary to decode the `TransactionMeta` being the field that contains the contracts invocations results. 

## Objective

Add all the required files to allow the encode and decode of TransactionMeta's

**Comment by miguelnietoa** [comment]
ℹ️  Released in [`v0.13.0`](https://github.com/kommitters/stellar_base/releases/tag/v0.13.0)
