### ISSUE TITLE
Add www.bestpractices.dev to scorecards workflow

### ISSUE THREAD

**Issue by miguelnietoa** [kommitters/stellar_base#297]
### Precheck

- [x] Do a quick search and make sure the bug has not been reported yet.
- [x] Please disclose security vulnerabilities privately at [oss@kommit.co](mailto:oss@kommit.co).
- [x] Finally, be nice and have fun!

### Description

The scorecard score is being affected (see below) because the `www.bestpractices.dev` endpoint is being blocked by harden-runner github action in the scorecards workflow. We need to include it to fix this.
![image](https://github.com/kommitters/stellar_base/assets/39246879/e474adf5-04a9-423d-9521-26c36c25dd29)

### Environment

* Elixir & Erlang/OTP versions (elixir --version):
* Operating system:

### Current behavior

`www.bestpractices.dev` is blocked.

### Expected behavior

`www.bestpractices.dev` should be allowed.

**Comment by CristhianRodriguezMolina** [comment]
:rocket: This was fixed on [v0.15.0](https://github.com/kommitters/stellar_base/releases/tag/v0.15.0)
